;; autogenerated via: (flycheck-checker-shell-command 'emacs-lisp)

(with-demoted-errors "Error during package initialization: %S"
  (package-initialize)
  (package-refresh-contents)
  (package-install `flycheck))

(defvar jka-compr-inhibit)

(unwind-protect
    (let ((jka-compr-inhibit t))
      (when (equal (car command-line-args-left) "--")
        (setq command-line-args-left (cdr command-line-args-left)))
      (defvar flycheck-byte-compiled-files nil)
      (let ((byte-compile-dest-file-function
             (lambda (source)
               (let ((temp-file (make-temp-file (file-name-nondirectory source))))
                 (push temp-file flycheck-byte-compiled-files) temp-file))))
        (unwind-protect (byte-compile-file (car command-line-args-left))
          (mapc (lambda (f) (ignore-errors (delete-file f)))
                flycheck-byte-compiled-files))
        (when (bound-and-true-p flycheck-emacs-lisp-check-declare)
          (check-declare-file (car command-line-args-left)))))
  (setq command-line-args-left nil))
